{% set name = "flowermd" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmelab/flowerMD/archive/{{ version }}.tar.gz
  sha256: e4b2857c58d9f8a9e4863b789224bdfd9325a703dc5c3482f11b16adc1a621dd 

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - foyer >=0.12.0
    - freud >=2.13.1
    - grits >=0.3.0
    - cmeutils >=1.0
    - gsd >=3.0
    - gmso >=0.11.2
    - hoomd >=4.0
    - mbuild >=0.16.4
    - numpy
    - openbabel >=3
    - py3Dmol
    - fresnel >=0.13.5

test:
  imports:
    - flowermd

about:
  home: https://github.com/cmelab/flowerMD
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Flexible library of organic workflows and extensible recipes for molecular dynamics."
  description: |
    flowerMD is a modular wrapper package for molecular dynamics (MD)
    simulation pipeline development, designed to enable fast, reproducible,
    end-to-end simulation workflows with minimal user effort.
  dev_url: https://github.com/cmelab/flowerMD 
  doc_url: https://flowermd.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - chrisjonesBSU
    - marjanAlbouye
    - erjank
