{% set name = "flowermd" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmelab/flowerMD/archive/{{ version }}.tar.gz
  sha256: 92c740f561f9bde274dbfae4f640e3098563950a620b89b031c6423491496e91

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1 
  noarch: python

requirements:
  host:
    - python >=3.10, <3.13
    - pip
  run:
    - python >=3.10, <3.13
    - foyer >=0.12.0
    - freud >=3.0
    - grits >=0.5.0
    - cmeutils >=1.3
    - gsd >=3.0
    - gmso >=0.12.0
    - hoomd >=4.5, <5.0
    - mbuild >0.17.0
    - numpy
    - openbabel >=3
    - py3Dmol
    - fresnel >=0.13.5

test:
  imports:
    - flowermd

about:
  home: https://github.com/cmelab/flowerMD
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Flexible library of organic workflows and extensible recipes for molecular dynamics."
  description: |
    flowerMD is a modular wrapper package for molecular dynamics (MD)
    simulation pipeline development, designed to enable fast, reproducible,
    end-to-end simulation workflows with minimal user effort.
  dev_url: https://github.com/cmelab/flowerMD
  doc_url: https://flowermd.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - chrisjonesBSU
    - marjanalbooyeh
    - erjank
