{% set python_min = '3.10' %}
{% set name = "flowermd" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmelab/flowerMD/archive/{{ version }}.tar.gz
  sha256: f1cf906a0af1e150de7a7d727c43f29e9e9edee0fa04b2e529415f775274ee9a 

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0 
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }},<3.13
    - foyer >=0.12.0
    - freud >=3.0
    - grits >=0.5.0
    - cmeutils >=1.3
    - gsd >=3.0
    - gmso >=0.12.0
    - hoomd >=4.6
    - mbuild >0.17.0
    - numpy <2.0
    - openbabel >=3
    - py3Dmol
    - fresnel >=0.13.5

test:
  requires:
    - python {{ python_min }}
  imports:
    - flowermd

about:
  home: https://github.com/cmelab/flowerMD
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Flexible library of organic workflows and extensible recipes for molecular dynamics."
  description: |
    flowerMD is a modular wrapper package for molecular dynamics (MD)
    simulation pipeline development, designed to enable fast, reproducible,
    end-to-end simulation workflows with minimal user effort.
  dev_url: https://github.com/cmelab/flowerMD
  doc_url: https://flowermd.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - chrisjonesBSU
    - marjanalbooyeh
    - erjank
